src/apps/accounts/urls.py
from .views import auth_login, auth_logout, thanks, registration, \
    reset_password, activate, set_password
from .ajax import save_profile
from django.conf.urls import url


urlpatterns = [
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
    url(r'^thanks/$', thanks, name='thanks'),
    url(r'^profile/save/$', save_profile, name='save_profile'),
    url(r'^profile/$', save_profile, name='show_profile'),
    url(r'^registration/$', registration, name='registration'),
    url(r'^reset_password/$', reset_password, name='reset_password'),
    url(r'^activate/(?P<key>\w+)$', activate, name='activate'),
    url(r'^set_password/(?P<key>\w+)$', set_password, name='set_password'),
]

src/django_base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^pages/', include('apps.pages.urls', namespace='pages')),
    url(r'^news/', include('apps.news.urls', namespace='news')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

admin.site.index_title = _('Панель администратора')
admin.site.site_header = admin.site.site_title = 'DjangoBase'

src/apps/accounts/models.py
from hashlib import md5
from django.db import models
from datetime import datetime
from django_base.db import ImgThumbsField
from django.core.validators import MaxLengthValidator
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError(_('У пользователя должен быть email адрес'))
        if not username:
            raise ValueError(_('У пользователя должно быть имя'))

        user = self.model(username=username, email=self.normalize_email(email))

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email,  password):
        user = self.create_user(username, email, password=password)
        user.is_admin = user.is_superuser = user.is_active = user.is_approved = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(_('Имя пользователя'), max_length=16, unique=True)
    email = models.EmailField(_('E-mail'), max_length=64, unique=True)
    avatar = ImgThumbsField(
        _('Аватар'),
        sizes={
            '64x64': ('min', 80),
            '128x128': ('mid', 80),
            '512x512': ('full', 80)
        },
        upload_to='accounts/',
        blank=True
    )
    fname = models.CharField(_('Имя'), max_length=50, blank=True)
    lname = models.CharField(_('Фамилия'), max_length=50, blank=True)
    info = models.TextField(_('Дополнительная информация'), validators=[MaxLengthValidator(512)], blank=True)
    key = models.CharField(_('UID'), max_length=64, blank=True, unique=True)
    is_active = models.BooleanField(_('Запись активирована'), default=False)
    is_admin = models.BooleanField(_('Администратор'), default=False)
    is_approved = models.BooleanField(_('Аккаунт подтвержден'), default=False)
    is_superuser = models.BooleanField(_('Привилегированный пользователь'), default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        db_table = 'accounts'
        verbose_name = 'пользователя'
        verbose_name_plural = 'Пользователи'

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self._gen_hash()
        super(CustomUser, self).save(*args, **kwargs)

    def __str__(self):
        return '%s (%s)' % (self.username, self.email)

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return '%s, %s' % (self.name, self.surname)

    def get_email(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def _gen_hash(self):
        return md5(
            str(
                '%s + %s + %s' % (self.username, self.email, str(datetime.utcnow()))
            ).encode('utf-8')
        ).hexdigest()

    @property
    def is_staff(self):
        return self.is_admin

src/apps/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ProfileForm(forms.Form):
    avatar = forms.FileField(required=False)
    username = forms.CharField(min_length=2, max_length=64, required=True)
    email = forms.EmailField(min_length=6, max_length=32, required=True)
    fname = forms.CharField(min_length=2, max_length=64, required=False)
    lname = forms.CharField(min_length=2, max_length=64, required=False)
    info = forms.CharField(min_length=2, max_length=512, required=False)


class LoginForm(forms.Form):
    username = forms.CharField(
        label=_('Имя пользователя'), min_length=2, max_length=64, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label=_('Пароль'), min_length=6, max_length=32, required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    remember_me = forms.BooleanField(
        label=_('Запомнить меня'),
        widget=forms.CheckboxInput(),
        required=False,
        initial=True
    )


class RegForm(forms.Form):
    username = forms.CharField(
        label=_('Имя пользователя'), min_length=3, max_length=32, required=True,
        widget=forms.TextInput(attrs={'class': 'col-md-10 form-control'})
    )
    email = forms.EmailField(
        label=_('E-mail'), min_length=6, max_length=32, required=True,
        widget=forms.TextInput(attrs={'class': 'col-md-10 form-control'})
    )
    password1 = forms.CharField(
        label=_('Пароль'), min_length=6, max_length=32, required=True,
        widget=forms.PasswordInput(attrs={'class': 'col-md-10 form-control'}),
    )
    password2 = forms.CharField(
        label=_('Подтверждение пароля'), min_length=6, max_length=32, required=True,
        widget=forms.PasswordInput(attrs={'class': 'col-md-10 form-control'}),
    )


class ResetPasswordForm(forms.Form):
    email = forms.EmailField(
        label=_('E-mail'), min_length=6, max_length=32, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )


class SetPasswordForm(forms.Form):
    password1 = forms.CharField(
        label=_('Пароль'), min_length=6, max_length=32, required=True,
        widget=forms.PasswordInput(attrs={'class': 'col-md-10 form-control'}),
    )
    password2 = forms.CharField(
        label=_('Подтверждение пароля'), min_length=6, max_length=32, required=True,
        widget=forms.PasswordInput(attrs={'class': 'col-md-10 form-control'}),
    )

src/apps/accounts/views.py
from django.shortcuts import render
from django.db import IntegrityError
from django_base.utils import send_email
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect
from django_base.settings import SITE_NAME
from .models import CustomUser
from .forms import LoginForm, RegForm, ResetPasswordForm, SetPasswordForm


def auth_login(request):
    '''
    Авторизация пользователя
    '''
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))

    if request.method == 'GET':
        form = LoginForm()
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            remember_me = form.cleaned_data['remember_me']
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)

                    # Если не поставлена галочка "запомнить меня"
                    if not remember_me:
                        request.session.set_expiry(0)

                    return HttpResponseRedirect(reverse('index'))
            else:
                return render(
                    request,
                    "error.html",
                    {
                        "error_title": _('Ошибка авторизации!'),
                        "error_description": _('Вероятно, вы ввели некорректное имя пользователя и/или пароль.')
                    }
                )
    else:
        return HttpResponseNotAllowed()

    return render(request, 'login.html', {'form': form})


def auth_logout(request):
    '''
    Выход пользователя
    '''
    logout(request)
    return HttpResponseRedirect(reverse('accounts:login'))


def registration(request):
    '''
    Регистрация нового пользователя
    '''
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))

    if request.method == 'GET':
        form = RegForm()
    elif request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            username = '%s' % form.cleaned_data['username']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            # Check username
            try:
                user = CustomUser.objects.get(username=username)

                return render(
                    request,
                    "error.html",
                    {
                        "error_title": _('Ошибка регистрации!'),
                        "error_description": _('Пользователь с именем \'%s\' уже существует!' % username)
                    }
                )
            except ObjectDoesNotExist:
                pass

            # Check e-mail
            try:
                user = CustomUser.objects.get(email=email)

                return render(
                    request,
                    "error.html",
                    {
                        "error_title": _('Ошибка регистрации!'),
                        "error_description": _('Пользовательс с e-mail \'%s\' уже существует!' % email)
                    }
                )
            except ObjectDoesNotExist:
                pass

            # Check password
            if password1 == password2:
                user = CustomUser.objects.create_user(username, email, password1)

                subject = _('Подтверждение регистрации')
                link = SITE_NAME+'/accounts/activate/%s' % user.key

                html = render_to_string(
                    'mail/registration_confirm.html',
                    {
                        'subject': subject,
                        'link': link,
                        'host': SITE_NAME
                    }
                )

                if not send_email(subject, html, email):
                    return render(
                        request,
                        "error.html",
                        {
                            "error_title": _('Ошибка регистрации!'),
                            "error_description": _('''
                                При отправки регистрационного письма возникла ошибка.
                                Пожалуйста, попробуйье повторить позднее!
                            ''')
                        }
                    )

                return HttpResponseRedirect(reverse('accounts:thanks'))
            else:
                return render(
                    request,
                    "error.html",
                    {
                        "error_title": _('Ошибка регистрации!'),
                        "error_description": _('Пароли не совпадают!')
                    }
                )
    else:
        return HttpResponseNotAllowed()

    return render(request, 'registration.html', {'form': form})


def activate(request, key):
    '''
    Проверка рег.ссылки и активирование учетной записи пользователя
    '''
    if request.user.is_active:
        return HttpResponseRedirect(reverse('index'))

    try:
        user = CustomUser.objects.get(key=key)
        user.is_active = True
        user.key = user._gen_hash()
        user.save()
        login(request, user)
    except IntegrityError:
        return render(
            request,
            "error.html",
            {
                "error_title": _('Ошибка активации!'),
                "error_description": _('Невозможно обновить данные пользователя!')
            }
        )
    except ObjectDoesNotExist:
        return render(
            request,
            "error.html",
            {
                "error_title": _('Ошибка активации!'),
                "error_description": _('Попытка регистрации по несуществующему или устаревшему ключу!')
            }
        )

    return render(request, "activated.html")


def set_password(request, key):
    '''
    Задание нового пароля пользователя
    '''
    if request.user.is_active:
        return HttpResponseRedirect(reverse('index'))
    try:
        user = CustomUser.objects.get(key=key)
        if request.method == 'POST':
            form = SetPasswordForm(request.POST)
            if form.is_valid():
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 == password2:
                    user.set_password(password1)
                    user.save()
                    return HttpResponseRedirect(reverse('accounts:login'))
                else:
                    return HttpResponseRedirect(reverse('accaunts:set_password', kwargs={'key': key}))
        else:
            form = SetPasswordForm()
        return render(request, 'set_password.html', {'form': form, 'key': key})
    except ObjectDoesNotExist:
        return render(
            request,
            "error.html",
            {
                "error_title": _('Ошибка восстановления!'),
                "error_description": _('Попытка восстановления пароля для несуществующего пользователя!')
            }
        )
    return HttpResponseRedirect(reverse('accounts:login'))


def reset_password(request):
    '''
    Сброс старого пароля пользователя
    '''
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))

    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = CustomUser.objects.get(email=email)
                subject = _('Создание нового пароля для BlankDJP')
                link = '127.0.0.1:8000/accounts/set_new_password/%s' % user.key
                html = render_to_string('mail/reset_password_confirm.html', {
                    'subject': subject, 'link': link,
                })
                sending_result = send_email(subject, html, email)

                if not sending_result:
                    return render(
                        request,
                        "error.html",
                        {
                            "error_title": _('Ошибка изменения пароля!'),
                            "error_description": _('''
                                При отправки регистрационного письма возникла ошибка.
                                Пожалуйста, попробуйье повторить позднее!
                            ''')
                        }
                    )

                return HttpResponse(_('На указзанный e-mail были отправлены Ваши пользовательские данные.'))
            except ObjectDoesNotExist:
                return render(
                    request,
                    "error.html",
                    {
                        "error_title": _('Ошибка изменения пароля!'),
                        "error_description": _('Пользователь с email \'%s\' не зарегистрирован!' % email)
                    }
                )
    else:
        form = ResetPasswordForm()
    return render(request, 'reset_password.html', {'form': form})


def thanks(request):
    '''
    Страница сообщения, что аккаунт зарегистрирован, письмо отправлено
    '''
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('index'))
    return render(request, 'thanks.html')


def show_profile(request):
    '''
    Страница обновление профиля пользователя
    '''
    return render(request, 'profile.html')

src/apps/accounts/templates/activated.html
{% extends "layouts/layout1.html" %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{% trans "Учетная запись активирована" %}{% endblock %}

{% block container %}
<div class="row">
	<div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 well center-block none-float">
		<h3>{% trans "Учетная запись активирована!" %}</h3>
		<p>{% trans "Вы успешно авторизовались" %}</p>
		<p><a href="{% url "index" %}">{% trans "Перейти на главную" %}</a>.</p>
	</div>
</div>
{% endblock %}

src/apps/accounts/templates/error.html
{% extends "layouts/layout1.html" %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{{ error_title }}{% endblock %}

{% block container %}
<div class="row">
	<div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 well center-block none-float">
		<h3 class="error"><span class="glyphicon glyphicon-remove"></span>&nbsp;{{ error_title }}</h3>
		<p>
			{{ error_description }}
		</p>
		<p><a href="{% url "index" %}">{% trans "Перейти на главную" %}</a>.</p>
	</div>
</div>
{% endblock %}

src/apps/accounts/templates/login.html
{% extends "layouts/layout1.html" %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{% trans "Форма входа" %}{% endblock %}

{% block styles %}{% endblock %}
 
{% block container %}
	<div class="row">
		<div class="well col-xs-12 col-sm-10 col-md-8 col-lg-6 center-block none-float">
			<form action="{% url "accounts:login" %}" method="POST" class="form-horizontal">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<fieldset>
					<legend><span class="glyphicon glyphicon-user"></span>&nbsp;{% trans "Форма входа" %}</legend>
					<div class="form-group">
						{{ form.username.errors }}
						<label for="{{ form.username.id_for_label }}" class="col-xs-4 col-md-3 col-lg-4 control-label">
							<sup class="require">*</sup>{% trans "Имя пользователя" %}
						</label>
						<div class="col-xs-8 col-md-9 col-lg-8">
							{{ form.username }}
						</div>
					</div>
					<div class="form-group">
						{{ form.password.errors }}
						<label for="{{ form.password.id_for_label }}" class="col-xs-4 col-md-3 col-lg-4 control-label">
							<sup class="require">*</sup>{% trans "Пароль" %}
						</label>
						<div class="col-xs-8 col-md-9 col-lg-8">
							{{ form.password }}
						</div>
					</div>
					<div class="form-group">
						<div class="col-xs-8 col-xs-offset-4 col-md-9 col-md-offset-3 col-lg-8 col-lg-offset-4">
							<div class="checkbox">
								<label>
									{{ form.remember_me }}&nbsp;{% trans "Запомнить меня" %}
								</label>
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-xs-12">
							<button type="submit" class="btn btn-primary">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;{% trans "Войти" %}
							</button>&nbsp;
							<a href="{% url "accounts:reset_password" %}" class="hidden-xs">{% trans "Забыли пароль?" %}</a>
							<a href="{% url "index" %}" role="button" class="btn btn-default pull-right">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;{% trans "Отмена" %}</a>
							<div class="clearfix"></div><br/>
							<a href="{% url "accounts:reset_password" %}" class="visible-xs">{% trans "Забыли пароль?" %}</a><br/>
							<a href="{% url "accounts:registration" %}">{% trans "Нет аккаунта? Зарегистрируйтесь!" %}</a>
						</div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
{% endblock %}

{% block scripts %}{% endblock %}

src/apps/accounts/templates/profile.html
{% extends "layouts/layout1.html" %}
{% load staticfiles %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{% trans "Профиль пользователя" %}{% endblock %}

{% block styles %}
	<link href="{% static "app/css/profile.css" %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block container %}
	<div class="row">
		<div class="well col-xs-12 col-sm-10 center-block none-float">
			<form id="profile-form" action="{% url "accounts:save_profile" %}" method="POST" class="form-horizontal" novalidate>
				{% csrf_token %}
				<fieldset class="center-block">
					<legend class="col-xs-12">
						<span class="glyphicon glyphicon-user"></span>&nbsp;{% trans "Профиль пользователя" %}
					</legend>

					<div class="col-xs-12 col-sm-10 col-md-4">
						<img id="avatar" src="{% if request.user.avatar %}{{ request.user.avatar.url_full }}{% else %}{% static "app/img/avatar.svg" %}{% endif %}" class="img-thumbnail center-block" alt="{% trans "Аватар" %}" />
						<div class="clearfix"></div><br/>
						<label class="col-xs-12 col-sm-12 btn btn-success center-block">
							<span class="glyphicon glyphicon-camera"></span>&nbsp;{% trans "Выбрать" %}
							<input name="avatar" type="file" style="display: none;">
						</label>
					</div>

					<div class="visible-xs visible-sm"><div class="clearfix"></div><br/></div>
					
					<div class="col-xs-12 col-sm-10 col-md-8">
						<h5>{% trans "Регистрационная информация" %}</h5>
						
						<div class="col-xs-11 col-md-10 form-group">
							<input class="form-control" type="text" name="username" value="{{ request.user.username }}" placeholder="{% trans "Имя пользователя" %}" maxlength="50" disabled />
						</div>
						<div class="col-xs-1 col-md-2">
							<button id="edit-username-btn" class="btn btn-success">
								<span class="glyphicon glyphicon-pencil"></span>
							</button>
						</div>
						<div class="clearfix"></div>

						<div class="col-xs-11 col-md-10 form-group">
							<input class="form-control" type="email" name="email" value="{{ request.user.email }}" placeholder="{% trans "E-mail" %}" maxlength="50" disabled />
						</div>
						<div class="col-xs-1 col-md-2">
							<button id="edit-email-btn" class="btn btn-success">
								<span class="glyphicon glyphicon-pencil"></span>
							</button>
						</div>

						<div class="clearfix"></div><br/>

						<h5>{% trans "Дополнительная информация" %}</h5>
						<div class="col-xs-12 col-md-10 form-group">
							<input class="form-control" type="text" name="fname" value="{{ request.user.fname }}" placeholder="{% trans "Имя" %}" maxlength="50" />
						</div>
						<div class="col-xs-12 col-md-10 form-group">
							<input class="form-control" type="text" name="lname" value="{{ request.user.lname }}" placeholder="{% trans "Фамилия" %}" maxlength="50" />
						</div>
						<div class="col-xs-12 col-md-10 form-group">
							<input class="form-control" type="text" name="info" value="{{ request.user.info }}" placeholder="{% trans "Дополнительная информация" %}" maxlength="512" />
						</div>

						<div class="col-xs-12 col-md-10 form-group">
							<button id="submit" type="button" class="btn btn-primary">
								<span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;{% trans "Сохранить" %}
							</button>
							<a href="{% url "index" %}" role="button" class="btn btn-default pull-right">
								<span class="glyphicon glyphicon-remove-circle"></span>&nbsp;{% trans "Отмена" %}
							</a>
						</div>

					</div>
				</fieldset>
			</form>

			<div class="col-xs-12">
				<div id="errors-block" class="col-xs-12 alert alert-danger" role="alert"></div>
			</div>
			<div class="clearfix"></div>

			<div class="modal fade saved-ok-modal" tabindex="-1" role="dialog" aria-labelledby="saved-ok-modal">
				<div class="modal-dialog modal-sm" role="document">
					<div class="modal-content">{% trans "Настройки профиля сохранены" %}</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script type="text/javascript" src="{% static "app/js/profile.js" %}"></script>
	<script type="text/javascript">Profile.init();</script>
{% endblock %}

src/apps/accounts/templates/registration.html
{% extends "layouts/layout1.html" %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{% trans "Регистрация" %}{% endblock %}

{% block styles %}
{% endblock %}

{% block container %}
	<div class="row">
		<div class="well col-xs-12 col-sm-10 col-md-8 col-lg-7 center-block none-float">
			<form action="{% url "accounts:registration" %}" method="POST" class="form-horizontal">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<fieldset>
					<legend>
						<span class="glyphicon glyphicon-user"></span>&nbsp;{% trans "Форма регистрации" %}
					</legend>
					<div class="form-group">
						{{ form.username.errors }}
						<label for="{{ form.username.id_for_label }}" class="col-xs-12 col-sm-4 col-md-4 col-lg-4 control-label">
							<sup class="require">*</sup>{% trans "Имя пользователя" %}
						</label>
						<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							{{ form.username }}
						</div>
					</div>
					<div class="form-group">
						{{ form.email.errors }}
						<label for="{{ form.email.id_for_label }}" class="col-xs-12 col-sm-4 col-md-4 col-lg-4 control-label">
							<sup class="require">*</sup>E-mail
						</label>
						<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							{{ form.email }}
						</div>
					</div>
					<div class="form-group">
						{{ form.password1.errors }}
						<label for="{{ form.password1.id_for_label }}" class="col-xs-12 col-sm-4 col-md-4 col-lg-4 control-label">
							<sup class="require">*</sup>{% trans "Пароль" %}
						</label>
						<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							{{ form.password1 }}
						</div>
					</div>
					<div class="form-group">
						{{ form.password2.errors }}
						<label for="{{ form.password2.id_for_label }}" class="col-xs-12 col-sm-4 col-md-4 col-lg-4 control-label">
							<sup class="require">*</sup>{% trans "Подтверждение пароля" %}
						</label>
						<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							{{ form.password2 }}
						</div>
					</div>
					<div class="hidden-xs form-group">
						<div class="col-xs-12 col-sm-8 col-sm-offset-4 col-md-8 col-md-offset-4 col-lg-8 col-lg-offset-4">
							<button type="submit" class="btn btn-primary">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;{% trans "Зарегистрироваться" %}
							</button>&nbsp;&nbsp;&nbsp;
							<a href="{% url "index" %}" role="button" class="btn btn-default">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;{% trans "Отмена" %}
							</a>
						</div>
					</div>
					<div class="visible-xs form-group">
						<div class="col-xs-12">
							<button type="submit" class="btn btn-primary col-xs-12">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>&nbsp;{% trans "Зарегистрироваться" %}
							</button>
							<div class="clearfix"></div><br/>
							<a href="{% url "index" %}" role="button" class="btn btn-default col-xs-12">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp;{% trans "Отмена" %}
							</a>
						</div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}

src/apps/accounts/templates/thanks.html
{% extends "layouts/layout1.html" %}
{% load i18n %}

{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block title %}{% trans "Благодарим за регистрацию" %}{% endblock %}

{% block container %}
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 well center-block none-float">
			<h3>{% trans "Блогодарим за регистрацию!" %}</h3>
			<p>{% trans "На указанный Вами e-mail выслано письмо с подтверждением." %}</p>
			<p>{% trans "Для продолжения регистрации, пожалуйста, перейдите по ссылке, указанной в письме." %}</p>
			<p><a href="{% url "index" %}">{% trans "Перейти на главную" %}</a>.</p>
		</div>
	</div>
{% endblock %}