src/apps/accounts/urls.py
from .views import auth_login, auth_logout, thanks, registration, \
    reset_password, activate, set_password
from .ajax import save_profile
from django.conf.urls import url


urlpatterns = [
    url(r'^login/$', auth_login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
    url(r'^thanks/$', thanks, name='thanks'),
    url(r'^profile/save/$', save_profile, name='save_profile'),
    url(r'^profile/$', save_profile, name='show_profile'),
    url(r'^registration/$', registration, name='registration'),
    url(r'^reset_password/$', reset_password, name='reset_password'),
    url(r'^activate/(?P<key>\w+)$', activate, name='activate'),
    url(r'^set_password/(?P<key>\w+)$', set_password, name='set_password'),
]

src/django_base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^pages/', include('apps.pages.urls', namespace='pages')),
    url(r'^news/', include('apps.news.urls', namespace='news')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

admin.site.index_title = _('Панель администратора')
admin.site.site_header = admin.site.site_title = 'DjangoBase'

src/templates/base.html
{% load i18n %}
{% load staticfiles %}
{% load pages_tags %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="{% block description %}{% endblock %}">
		<meta name="keywords" content="{% block keywords %}{% endblock %}">
		<meta name="author" content="Peter P. Neuromantic <peter.brovchenko@gmail.com>">
		<link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
		<title>DjnagoBase - {% block title %}{% endblock %}</title>
		<link href="{% static "deps/bootstrap/css/bootstrap.min.css" %}" type="text/css" rel="stylesheet">
		<link href="{% static "app/css/style.css" %}" type="text/css" rel="stylesheet">
		{% block styles %}{% endblock %}
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<div class="navbar-brand">
						<a href="{% url 'index' %}">
							<img id="djb-logo" src="{% static "app/img/logo.png" %}" alt="DjangoBase logo" />
							<span class="navbar-brand-title">DjangoBase</span>
						</a>
					</div>
				</div>
				<div id="navbar" class="collapse navbar-collapse">

					{% top_menu request %}
					
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								{% trans "Язык" %} <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								{% for lang in LANGUAGES %}
									<li>
										<form name="setLang{{ lang.1}}" action="/i18n/setlang/" method="POST">
											{% csrf_token %}
											<input name="next" type="hidden" value="{{ request.path }}" />
											<input type="hidden" name="language" value="{{ lang.0 }}" />
											<a href="#" onclick="document.setLang{{ lang.1 }}.submit();return false;">
												{{ lang.1 }}
											</a>
										</form>
									</li>
								{% endfor %}
							</ul>
						</li>
						{% if request.user.is_authenticated %}
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="{% url "accounts:show_profile" %}">{% trans "Профиль" %}</a></li>
									<li role="separator" class="divider"></li>
									<li><a href="{% url 'accounts:logout' %}">{% trans "Выйти" %}</a></li>
								</ul>
							</li>
						{% else %}
							<li><a href="{% url "accounts:login" %}">{% trans "Войти" %}</a></li>
							<li><a href="{% url "accounts:registration" %}">{% trans "Зарегистрироваться" %}</a></li>
						{% endif %}
						<form class="navbar-form navbar-left">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="{% trans "Поиск" %}">
							</div>
							<button type="submit" class="btn btn-default">
								<span class="glyphicon glyphicon-search"></span>
							</button>
						</form>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		{% block main %}
		{% endblock %}

		<footer class="footer">
			<div class="container">
				<p class="text-muted">
					All rights reserved. DjangoBase CopyRight &copy; 2016-{% now "Y" %}
				</p>
			</div>
		</footer>
		
		<script type="text/javascript" src="{% static "deps/jquery/jquery-3.3.1.slim.min.js" %}"></script>
		<script type="text/javascript" src="{% static "deps/bootstrap/js/bootstrap.min.js" %}"></script>
		<script type="text/javascript" src="{% static "app/js/script.js" %}"></script>
		{% block scripts %}{% endblock %}
	</body>
</html>

<!-- EOF -->