src/apps/news/urls.py
from django.conf.urls import url
from .views import news_list, news_detail


urlpatterns = [
    url(r"^$", news_list, name="news_list"),
    url(r"^(?P<pk>\d+)/$", news_detail, name="news_detail"),
]

src/apps/pages/urls.py
from django.conf.urls import url
from .views import show_page


urlpatterns = [
    url(r"^(?P<slug>[\w-]+)/$", show_page, name='show_page'),
]

# EOF

src/django_base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^pages/', include('apps.pages.urls', namespace='pages')),
    url(r'^news/', include('apps.news.urls', namespace='news')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

admin.site.index_title = _('Панель администратора')
admin.site.site_header = admin.site.site_title = 'DjangoBase'

src/apps/pages/templates/units/top_menu.html
{% load i18n %}
{% load mptt_tags %}

<ul class="nav navbar-nav">
	{% if is_news %}
		<li><a href="{% url "news:news_list" %}">{% trans "Новости" %}</a></li>
	{% endif %}
	{% if menu_list %}
		{% recursetree menu_list %}
		{% if not node.is_leaf_node %}
			<li class="dropdown">
				<a href="#{{ node.slug }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
					{{ node.title }}&nbsp;<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					{{ children }}
				</ul>
			</li>
		{% else %}
			<li{% if if_active %} class="active"{% endif %}>
				<a href="{% if node.external_link %}{{ node.external_link }}{% else %}{% url "pages:show_page" node.slug %}{% endif %}">
					{{ node.title }}
				</a>
			</li>
			{% if node.is_separate %}
				<li role="separator" class="divider"></li>
			{% endif %}
		{% endif %}
        {% endrecursetree %}
	{% endif %}
</ul>